export const SENTENCES: string[] = [
    // ── short & simple ──
    "The sky is clear today.",
    "Time moves faster than we think.",
    "Practice makes everything better.",
    "The computer froze again.",
    "Coffee keeps me awake.",
    "Dreams inspire great ideas.",
    "Stay calm and keep going.",
    "Nothing lasts forever.",
    "The cat jumped over the box.",
    "Hard work always pays off.",
    "Fast typing requires rhythm and focus.",
    "Accuracy is more important than speed.",
    "Keep your eyes on the screen.",
    "Warm up your fingers before starting.",
    "Every second counts when the timer starts.",
    "Stay relaxed to maintain high accuracy.",
    "Speed grows naturally with consistent practice.",
    "Your hands know the keys better than your eyes.",
    "Challenge yourself to type faster every day.",
    "Mistakes help you improve your typing ability.",
    "A good morning starts with a clear mind.",
    "The sunset painted the sky in warm colors.",
    "Music can change the mood of an entire room.",
    "Silence is sometimes the best answer.",
    "A smile can brighten someone's entire day.",
    "The stars were unusually bright last night.",
    "Rain always makes the garden look greener.",
    "He finished his coffee before it got cold.",
    "The clock on the wall ticked quietly.",
    "She opened the window to let fresh air in.",
    "The road ahead was long but beautiful.",
    "He always carried a book in his backpack.",
    "The moon reflected softly on the calm lake.",
    "She hummed a tune while cooking dinner.",
    "The old bridge creaked under their weight.",
    "A warm blanket makes cold nights bearable.",
    "The birds sang louder as the sun rose higher.",
    "He waved goodbye and walked into the crowd.",
    "The candle flickered gently in the dark room.",
    "She found comfort in the sound of falling rain.",

    // ── medium length ──
    "Success is built from small, consistent efforts.",
    "The internet connection dropped unexpectedly.",
    "She found a hidden message inside the old book.",
    "Technology changes faster than people expect.",
    "Every challenge is an opportunity to grow.",
    "The weather forecast predicts heavy rain tonight.",
    "He spent hours practicing to perfect his skills.",
    "A single mistake can teach a valuable lesson.",
    "The train arrived earlier than scheduled today.",
    "Some problems require time and patience to solve.",
    "The robot malfunctioned during the final test.",
    "She accidentally deleted the entire project folder.",
    "The elevator stopped between the eighth and ninth floor.",
    "A loud thunderstorm interrupted the peaceful night.",
    "He received an unexpected message from an old friend.",
    "The last piece of the puzzle was hidden under the chair.",
    "They built a small campfire beside the quiet lake.",
    "The password was easy to remember but hard to guess.",
    "She typed so fast that the keyboard nearly overheated.",
    "The mystery box contained nothing but a single feather.",
    "He noticed a pattern in the data that no one else saw.",
    "The library was quiet except for the sound of turning pages.",
    "She organized her bookshelf by color instead of title.",
    "The old clock in the hallway stopped working at midnight.",
    "He left a sticky note on the fridge as a reminder.",
    "The streetlights flickered on as the evening grew darker.",
    "She packed her bag the night before to save time.",
    "The garden looked different after the first snow of winter.",
    "He checked his phone and realized he had missed three calls.",
    "The smell of fresh paint filled the newly renovated room.",
    "She kept a journal to track her thoughts and progress.",
    "The bus was late again, so he decided to walk instead.",
    "He found an old coin buried in the backyard soil.",
    "The restaurant was fully booked for the entire weekend.",
    "She noticed that the map was upside down the whole time.",
    "The power went out just as the movie reached its climax.",
    "He accidentally wore two different socks to the office.",
    "The vending machine swallowed his coin without giving anything.",
    "She discovered a shortcut that saved twenty minutes each day.",
    "The package arrived a day earlier than the estimated date.",

    // ── daily life ──
    "She woke up early to watch the sunrise from her balcony.",
    "The smell of fresh bread filled the small bakery every morning.",
    "He forgot his umbrella and got soaked in the heavy rain.",
    "The children laughed loudly as they ran through the park.",
    "He organized his desk to clear his mind before working.",
    "The alarm clock rang, but he pressed snooze three times.",
    "She wrote her goals on a small sticky note above her screen.",
    "The traffic was slower than usual because of the morning fog.",
    "He took a short walk to rest his eyes from the monitor.",
    "The tiny plant on the windowsill grew a new leaf today.",
    "She listened to soft music while reading her favorite novel.",
    "He cooked a simple meal and enjoyed the quiet evening.",
    "The cafe on the corner was crowded but surprisingly peaceful.",
    "She bought a new notebook to track her daily habits.",
    "He cleaned his room and found an old photo album.",
    "The dog barked excitedly when its owner entered the house.",
    "She wrote a letter instead of sending a quick text message.",
    "The classroom became silent as the exam papers were handed out.",
    "He saved money each month to travel to his dream destination.",
    "She watered the plants every morning before leaving for work.",
    "The neighbor's cat visited their porch every afternoon.",
    "He spent the weekend rearranging furniture in the living room.",
    "She made a playlist of songs that matched her current mood.",
    "The grocery store was out of his favorite brand of cereal.",
    "He fixed the leaking faucet using a tutorial he found online.",
    "She folded the laundry while watching a documentary on nature.",
    "The mailbox was full of letters he had forgotten to check.",
    "He set three alarms to make sure he would not oversleep.",
    "She baked cookies for her coworkers as a Friday surprise.",
    "The park bench was still wet from the morning dew.",
    "He walked his dog along the river path every evening.",
    "She rearranged her closet and donated clothes she no longer wore.",
    "The ice cream melted faster than he could eat it.",
    "He forgot to charge his phone and it died during lunch.",
    "She found a four-leaf clover while sitting in the grass.",
    "The elevator music was oddly relaxing on a stressful day.",
    "He accidentally locked himself out of his own apartment.",
    "She tried a new recipe and it turned out surprisingly well.",
    "The morning jog helped him think more clearly at work.",
    "She left a kind note inside her friend's lunchbox.",

    // ── work & study ──
    "He reviewed his notes carefully before the important presentation.",
    "She asked clear questions to understand the difficult topic better.",
    "The deadline was close, but the team stayed calm and focused.",
    "He divided the large project into smaller, manageable tasks.",
    "She stayed after class to practice and improve her weak points.",
    "The meeting took longer than expected but ended with a good plan.",
    "He double-checked the report for spelling and formatting mistakes.",
    "She highlighted the most important ideas in the textbook.",
    "They discussed different solutions before choosing the final approach.",
    "He realized that planning ahead reduced his overall stress.",
    "She used a timer to stay focused during her study sessions.",
    "He created a to-do list and actually finished every item on it.",
    "They shared feedback politely and helped each other improve.",
    "She practiced public speaking in front of a mirror every night.",
    "He searched for examples online to understand the problem clearly.",
    "The professor encouraged students to ask questions without feeling shy.",
    "She backed up all her files to avoid losing her progress.",
    "He learned that consistency beats short bursts of intense effort.",
    "They celebrated finishing the long project with a simple team lunch.",
    "She color-coded her calendar to separate work and personal tasks.",
    "He arrived at the office early to prepare for the morning meeting.",
    "The intern asked thoughtful questions that impressed the whole team.",
    "She rewrote the introduction three times before she was satisfied.",
    "He used flashcards to memorize vocabulary for the language exam.",
    "The group project required everyone to contribute equally.",
    "She scheduled breaks between study blocks to avoid burnout.",
    "He printed the slides and added handwritten notes in the margins.",
    "The workshop taught practical skills that textbooks often skip.",
    "She volunteered to present first to get it over with quickly.",
    "He organized his email inbox and deleted hundreds of old messages.",
    "The study group met every Wednesday evening at the campus library.",
    "She recorded the lecture so she could review it later at home.",
    "He learned to prioritize tasks based on urgency and importance.",
    "The feedback from the mentor helped her improve significantly.",
    "He submitted the assignment five minutes before the deadline.",
    "She created a shared document so the team could collaborate easily.",
    "The conference call had a slight delay but went smoothly overall.",
    "He took detailed notes during the training session for future reference.",
    "She asked her manager for feedback to identify areas for growth.",
    "The quarterly review showed steady improvement across all metrics.",

    // ── coding & tech ──
    "He spent an hour debugging a bug caused by a missing semicolon.",
    "The website looked fine on desktop but broke on mobile screens.",
    "She pushed her code to the repository and opened a pull request.",
    "The server restarted unexpectedly and logged a strange error message.",
    "He refactored messy functions into smaller, reusable components.",
    "She wrote unit tests to make sure the feature worked correctly.",
    "The app loaded faster after they optimized the API responses.",
    "He added helpful comments so others could understand the code easily.",
    "She learned that naming variables clearly saved time in the future.",
    "The dark theme of the editor helped reduce eye strain at night.",
    "He forgot to handle an edge case and the app crashed for some users.",
    "They reviewed each other's code and spotted subtle performance issues.",
    "She documented the setup steps to help new team members join quickly.",
    "He used version control to safely experiment with different approaches.",
    "The new feature passed all tests but failed in real user conditions.",
    "She used keyboard shortcuts to navigate the editor much faster.",
    "He monitored the logs to find patterns in the reported errors.",
    "They deployed the updated app and watched the metrics in real time.",
    "She fixed a bug that bothered users for several weeks.",
    "The database query took too long because it was missing an index.",
    "He automated the deployment process to reduce human error.",
    "She configured the linter to enforce consistent code formatting.",
    "The API returned an empty response instead of the expected data.",
    "He wrote a script to migrate data from the old system to the new one.",
    "She set up continuous integration to catch bugs before merging code.",
    "The frontend and backend teams had a sync meeting every morning.",
    "He used environment variables to keep sensitive data out of the code.",
    "She created a reusable component library to speed up development.",
    "The load balancer distributed traffic evenly across all servers.",
    "He added rate limiting to prevent abuse of the public API.",
    "She optimized the images to reduce the page load time significantly.",
    "The cache invalidation bug caused users to see outdated content.",
    "He wrote integration tests that covered the most critical user flows.",
    "She used a profiler to identify the slowest parts of the application.",
    "The SSL certificate expired and the site showed a security warning.",
    "He containerized the application using a simple configuration file.",
    "She implemented pagination to handle large datasets efficiently.",
    "The webhook failed silently because the endpoint URL had changed.",
    "He added logging at every critical step to make debugging easier.",
    "She refactored the authentication flow to support multiple providers.",
    "The memory leak was caused by event listeners that were never removed.",
    "He set up alerts to notify the team when error rates spiked.",
    "She migrated the project from a monolith to a microservices architecture.",
    "The build pipeline broke because a dependency released a breaking change.",
    "He wrote clear commit messages so the team could follow the project history.",

    // ── mindset & motivation ──
    "Small improvements made every day create big changes over time.",
    "He reminded himself that progress matters more than perfection.",
    "She started slowly but never stopped moving forward.",
    "Failure became a lesson instead of a final result.",
    "He chose to focus on what he could control.",
    "She learned to rest instead of completely giving up.",
    "They supported each other's goals and shared honest encouragement.",
    "He tracked his progress to stay motivated on difficult days.",
    "She realized that comparing herself to others only slowed her down.",
    "He took a deep breath before dealing with a stressful situation.",
    "She accepted that learning new skills feels uncomfortable at first.",
    "He focused on the process instead of worrying about the outcome.",
    "She noticed that gratitude made stressful days feel lighter.",
    "They celebrated small wins to keep their spirits high.",
    "He learned to say no to distractions that wasted his time.",
    "She replaced negative thoughts with simple, realistic statements.",
    "He paused for a moment to think before reacting emotionally.",
    "She wrote down three good things that happened each day.",
    "Discipline is choosing between what you want now and what you want most.",
    "The best time to start was yesterday, the next best time is now.",
    "He stopped waiting for the perfect moment and just began.",
    "She found strength in the routines she built over months.",
    "Growth happens outside the boundaries of your comfort zone.",
    "He learned that asking for help is a sign of strength, not weakness.",
    "She reminded herself that every expert was once a beginner.",
    "Consistency is more powerful than motivation on most days.",
    "He kept showing up even when the results were not visible yet.",
    "She trusted the process and let go of the need for instant results.",
    "The journey matters just as much as the destination.",
    "He realized that rest is part of the work, not the opposite of it.",

    // ── fun & quirky ──
    "The cat stared at the cursor moving across the bright screen.",
    "He accidentally sent a funny sticker to the wrong group chat.",
    "She laughed when the autocorrect completely changed her sentence.",
    "The phone battery died just before he could save the document.",
    "He tried to balance a cup of coffee and his laptop in one hand.",
    "She almost typed her password into the search bar.",
    "The notification sound interrupted the quiet room again.",
    "He found an old game that still worked perfectly on his computer.",
    "She bought a mechanical keyboard just for the typing sound.",
    "He took a screenshot instead of writing the information down.",
    "The progress bar stopped at ninety-nine percent and stayed there.",
    "She renamed a file three times before choosing a final name.",
    "He accidentally opened fifty browser tabs while researching one topic.",
    "The Wi-Fi disconnected right before the important online meeting.",
    "She muted all notifications to finish her work without interruption.",
    "He used a random name generator to create test user accounts.",
    "The cursor blinked on an empty line, waiting for an idea.",
    "She changed the wallpaper to make her desktop feel fresh again.",
    "He smiled when the test finally passed with a green checkmark.",
    "She closed her laptop and decided the day was finally over.",
    "The printer jammed at the worst possible moment during the deadline.",
    "He realized he had been typing in the wrong chat window for five minutes.",
    "She found a typo in the email right after pressing the send button.",
    "The loading spinner kept spinning but nothing ever loaded.",
    "He tried to undo his mistake but accidentally pressed redo instead.",
    "She discovered that her webcam had been on during the entire meeting.",
    "The autosave feature rescued his work after the unexpected crash.",
    "He spent ten minutes looking for his glasses while wearing them.",
    "She accidentally replied all to an email meant for one person.",
    "The software update took so long that he fell asleep waiting.",
    "He plugged in the USB cable upside down on the first two attempts.",
    "She forgot to unmute herself and talked for a full minute in silence.",
    "The file was too large to send by email so he used a cloud link.",
    "He named the folder 'final version' for the seventh time.",
    "She realized the bug was caused by a single misplaced comma.",
    "The keyboard shortcut he memorized saved him hours every week.",
    "He accidentally dragged a file to the wrong folder and panicked.",
    "She set a reminder but forgot what the reminder was for.",
    "The dark mode toggle became his favorite feature of the new app.",
    "He celebrated fixing the bug by immediately introducing a new one.",

    // ── longer / complex ──
    "Creativity often appears when we stop forcing ourselves to think.",
    "The old library was filled with dusty books and forgotten stories.",
    "She realized that confidence comes from experience, not perfection.",
    "When working under pressure, staying organized becomes essential.",
    "The city lights reflected beautifully across the quiet river at night.",
    "Even the most complicated tasks become manageable when broken into smaller steps.",
    "Learning a new language can be challenging, but it opens countless opportunities.",
    "He discovered that good communication prevents most misunderstandings.",
    "The scientist spent years studying tiny details that most people overlooked.",
    "Moments of silence often help the mind find clarity and focus.",
    "The best ideas often come from combining two completely unrelated concepts.",
    "She spent the afternoon organizing her digital files into a logical folder structure.",
    "He learned that writing things down helped him remember them much better than typing.",
    "The team agreed to limit meetings to thirty minutes to protect everyone's focus time.",
    "She noticed that her productivity peaked in the early morning hours before anyone else woke up.",
    "He built a habit tracker spreadsheet and filled it in every night before going to sleep.",
    "The documentary about deep ocean creatures changed the way she thought about the planet.",
    "He realized that the most valuable skill he could develop was the ability to learn quickly.",
    "She kept a separate notebook for random ideas that popped into her head during the day.",
    "The old photograph reminded him of a summer vacation he had almost completely forgotten.",
    "He discovered that taking a different route to work made his mornings feel less repetitive.",
    "She found that explaining a concept to someone else was the best way to truly understand it.",
    "The thunderstorm knocked out the power for three hours and he read a book by candlelight.",
    "He set up a second monitor and wondered how he ever worked with just one screen.",
    "She learned that saying thank you more often improved her relationships at work and at home.",
    "The bookstore on the corner had a cozy reading area with comfortable chairs and warm lighting.",
    "He automated his weekly report so he could spend that time on more meaningful work instead.",
    "She realized that the fear of starting was always worse than the actual work itself.",
    "The museum exhibit about ancient civilizations made him appreciate how far technology has come.",
    "He kept a list of books he wanted to read and crossed them off one by one throughout the year.",
];


export const WORDS: string[] = [
    // ── common / basic ──
    "the", "quick", "brown", "fox", "jumps", "over", "lazy", "dog", "cat", "bird",
    "coffee", "tea", "water", "juice", "milk", "bread", "rice", "salt", "sugar", "butter",
    "keyboard", "screen", "monitor", "mouse", "window", "door", "table", "chair", "desk", "lamp",
    "phone", "laptop", "notebook", "pencil", "paper", "folder", "office", "school", "library", "classroom",
    "teacher", "student", "friend", "family", "parent", "child", "brother", "sister", "neighbor", "stranger",
    "message", "email", "letter", "note", "card", "ticket", "receipt", "invoice", "report", "document",
    "character", "space", "enter", "shift", "control", "tab", "escape", "delete", "insert", "home",

    // ── typing / performance ──
    "typing", "practice", "speed", "accuracy", "rhythm", "effort", "focus", "energy", "habit", "routine",
    "progress", "result", "session", "warmup", "test", "sample", "target", "mistake", "correction", "timing",
    "reaction", "pressure", "performance", "stamina", "consistency", "improvement", "challenge", "record",
    "streak", "score", "rank", "level", "milestone", "benchmark", "threshold", "baseline", "peak", "plateau",

    // ── feelings / mindset ──
    "calm", "relaxed", "brave", "patient", "curious", "confident", "grateful", "careful", "focused", "motivated",
    "tired", "sleepy", "nervous", "excited", "optimistic", "hopeful", "quiet", "peaceful", "stress", "doubt",
    "fear", "courage", "growth", "joy", "pride", "relief", "surprise", "wonder", "comfort", "warmth",
    "happy", "sad", "angry", "confused", "bored", "inspired", "determined", "anxious", "content", "lonely",
    "cheerful", "gloomy", "restless", "satisfied", "frustrated", "amazed", "grateful", "jealous", "guilty", "proud",

    // ── time / schedule ──
    "time", "minute", "second", "hour", "morning", "noon", "evening", "night", "midnight", "dawn",
    "deadline", "schedule", "routine", "break", "moment", "today", "tomorrow", "yesterday", "later", "soon",
    "someday", "always", "never", "often", "rarely", "weekly", "daily", "monthly", "yearly", "instant",
    "duration", "interval", "period", "season", "spring", "summer", "autumn", "winter", "decade", "century",

    // ── colors ──
    "green", "red", "yellow", "blue", "black", "white", "purple", "orange", "pink", "gray",
    "gold", "silver", "bronze", "crimson", "navy", "teal", "coral", "ivory", "maroon", "violet",
    "indigo", "turquoise", "magenta", "scarlet", "amber", "emerald", "sapphire", "ruby", "pearl", "charcoal",

    // ── tech / coding ──
    "python", "typescript", "javascript", "react", "nextjs", "node", "server", "client", "frontend", "backend",
    "request", "response", "status", "error", "warning", "success", "failure", "debug", "feature", "commit",
    "branch", "merge", "deploy", "release", "version", "update", "rollback", "log", "console", "editor",
    "terminal", "command", "shortcut", "syntax", "runtime", "package", "module", "import", "export", "variable",
    "function", "constant", "array", "object", "string", "number", "boolean", "null", "undefined", "promise",
    "async", "await", "testcase", "coverage", "refactor", "cleanup", "database", "schema", "query", "index",
    "cache", "token", "session", "cookie", "header", "payload", "endpoint", "webhook", "socket", "stream",
    "pipeline", "container", "cluster", "instance", "volume", "network", "gateway", "proxy", "firewall", "router",
    "compiler", "interpreter", "debugger", "profiler", "linter", "formatter", "bundler", "transpiler", "loader", "plugin",
    "framework", "library", "toolkit", "platform", "service", "middleware", "handler", "listener", "emitter", "observer",
    "iterator", "generator", "decorator", "factory", "singleton", "adapter", "wrapper", "interface", "abstract", "generic",
    "algorithm", "recursion", "iteration", "callback", "closure", "scope", "context", "prototype", "inheritance", "polymorphism",
    "encryption", "hashing", "authentication", "authorization", "validation", "serialization", "parsing", "rendering", "hydration", "caching",

    // ── UI / design ──
    "button", "input", "label", "form", "layout", "margin", "padding", "border", "radius", "shadow",
    "hover", "active", "focus", "disabled", "icon", "avatar", "dropdown", "sidebar", "navbar", "footer",
    "header", "card", "panel", "dialog", "modal", "overlay", "tooltip", "badge", "chip", "divider",
    "grid", "flex", "stack", "container", "wrapper", "section", "article", "aside", "main", "navigation",
    "breadcrumb", "pagination", "carousel", "accordion", "tabs", "stepper", "slider", "toggle", "switch", "checkbox",
    "radio", "select", "textarea", "placeholder", "caption", "subtitle", "headline", "paragraph", "blockquote", "list",
    "thumbnail", "gallery", "lightbox", "skeleton", "spinner", "progress", "notification", "alert", "banner", "toast",

    // ── nature / places ──
    "river", "mountain", "forest", "ocean", "island", "village", "city", "bridge", "station", "harbor",
    "valley", "desert", "jungle", "meadow", "cliff", "canyon", "waterfall", "glacier", "volcano", "cave",
    "beach", "shore", "coast", "reef", "lagoon", "pond", "creek", "stream", "spring", "marsh",
    "garden", "field", "farm", "orchard", "vineyard", "prairie", "tundra", "savanna", "plateau", "ridge",
    "trail", "path", "road", "highway", "alley", "boulevard", "avenue", "lane", "tunnel", "overpass",
    "airport", "flight", "train", "bus", "subway", "ferry", "bicycle", "motorcycle", "truck", "van",

    // ── food & drink ──
    "apple", "banana", "grape", "lemon", "orange", "mango", "peach", "cherry", "berry", "melon",
    "tomato", "potato", "onion", "garlic", "pepper", "carrot", "spinach", "broccoli", "mushroom", "cucumber",
    "chicken", "salmon", "shrimp", "steak", "bacon", "sausage", "cheese", "yogurt", "cream", "honey",
    "pasta", "pizza", "burger", "sandwich", "salad", "soup", "curry", "sushi", "taco", "noodle",
    "chocolate", "vanilla", "caramel", "cinnamon", "ginger", "mint", "basil", "thyme", "oregano", "parsley",

    // ── animals ──
    "eagle", "hawk", "owl", "sparrow", "penguin", "dolphin", "whale", "shark", "turtle", "octopus",
    "rabbit", "squirrel", "deer", "wolf", "bear", "lion", "tiger", "elephant", "giraffe", "zebra",
    "monkey", "parrot", "snake", "frog", "butterfly", "beetle", "spider", "ant", "bee", "dragonfly",

    // ── household / objects ──
    "pillow", "blanket", "curtain", "carpet", "mirror", "shelf", "drawer", "cabinet", "closet", "hanger",
    "towel", "soap", "shampoo", "toothbrush", "razor", "comb", "brush", "sponge", "bucket", "basket",
    "candle", "lighter", "matches", "battery", "charger", "adapter", "cable", "plug", "socket", "switch",
    "clock", "watch", "calendar", "frame", "vase", "plant", "flower", "seed", "soil", "pot",

    // ── verbs ──
    "run", "walk", "sleep", "eat", "drink", "write", "read", "listen", "speak", "study",
    "learn", "practice", "repeat", "review", "focus", "plan", "organize", "create", "build", "design",
    "fix", "break", "open", "close", "save", "cancel", "submit", "upload", "download", "install",
    "remove", "replace", "update", "search", "filter", "sort", "group", "split", "merge", "connect",
    "disconnect", "attach", "detach", "expand", "collapse", "zoom", "scroll", "drag", "drop", "click",
    "type", "press", "hold", "release", "tap", "swipe", "pinch", "rotate", "shake", "tilt",
    "think", "decide", "choose", "compare", "measure", "calculate", "estimate", "predict", "analyze", "evaluate",
    "explain", "describe", "summarize", "translate", "interpret", "simplify", "clarify", "illustrate", "demonstrate", "prove",
    "accept", "reject", "approve", "deny", "confirm", "verify", "validate", "certify", "guarantee", "promise",
    "begin", "finish", "complete", "achieve", "accomplish", "succeed", "fail", "attempt", "retry", "recover",
    "improve", "enhance", "optimize", "maximize", "minimize", "reduce", "increase", "decrease", "maintain", "sustain",
    "discover", "explore", "investigate", "research", "experiment", "observe", "notice", "recognize", "identify", "detect",
    "collect", "gather", "assemble", "arrange", "distribute", "deliver", "ship", "transport", "transfer", "exchange",
    "protect", "defend", "guard", "secure", "shield", "preserve", "conserve", "restore", "repair", "heal",

    // ── adjectives ──
    "simple", "complex", "random", "manual", "automatic", "hidden", "visible", "public", "private", "global",
    "local", "smooth", "sharp", "fast", "slow", "early", "late", "basic", "advanced", "common",
    "rare", "similar", "different", "unique", "ordinary", "special", "regular", "unusual", "normal", "strange",
    "bright", "dark", "light", "heavy", "thick", "thin", "wide", "narrow", "deep", "shallow",
    "hot", "cold", "warm", "cool", "fresh", "stale", "clean", "dirty", "dry", "wet",
    "soft", "hard", "rough", "gentle", "strong", "weak", "tough", "fragile", "solid", "hollow",
    "loud", "quiet", "silent", "noisy", "clear", "blurry", "sharp", "dull", "vivid", "faint",
    "new", "old", "young", "ancient", "modern", "recent", "current", "previous", "next", "final",
    "tiny", "small", "medium", "large", "huge", "massive", "enormous", "giant", "miniature", "compact",
    "beautiful", "elegant", "graceful", "stunning", "gorgeous", "plain", "ugly", "messy", "neat", "tidy",
    "important", "essential", "critical", "vital", "necessary", "optional", "extra", "spare", "surplus", "sufficient",
    "perfect", "excellent", "great", "good", "decent", "average", "poor", "terrible", "awful", "horrible",
    "easy", "difficult", "tricky", "challenging", "impossible", "possible", "likely", "unlikely", "certain", "uncertain",
    "busy", "free", "available", "occupied", "empty", "full", "crowded", "spacious", "cozy", "cramped",

    // ── adverbs / connectors ──
    "quickly", "slowly", "carefully", "quietly", "loudly", "gently", "roughly", "smoothly", "suddenly", "gradually",
    "always", "never", "sometimes", "often", "rarely", "usually", "frequently", "occasionally", "constantly", "temporarily",
    "already", "still", "yet", "just", "almost", "nearly", "barely", "hardly", "completely", "partially",
    "exactly", "approximately", "roughly", "precisely", "literally", "basically", "essentially", "primarily", "mainly", "mostly",
    "however", "therefore", "meanwhile", "otherwise", "furthermore", "moreover", "nevertheless", "regardless", "instead", "besides",

    // ── abstract / concepts ──
    "idea", "concept", "theory", "principle", "method", "approach", "strategy", "technique", "process", "system",
    "pattern", "structure", "framework", "model", "template", "standard", "protocol", "guideline", "policy", "rule",
    "balance", "harmony", "contrast", "tension", "conflict", "resolution", "compromise", "agreement", "consensus", "debate",
    "freedom", "justice", "equality", "diversity", "integrity", "honesty", "loyalty", "respect", "trust", "wisdom",
    "knowledge", "experience", "skill", "talent", "ability", "potential", "capacity", "competence", "expertise", "mastery",
    "success", "failure", "victory", "defeat", "progress", "setback", "breakthrough", "obstacle", "barrier", "opportunity",
    "change", "stability", "innovation", "tradition", "evolution", "revolution", "transformation", "adaptation", "transition", "shift",
];

export function buildWordsText(count: number): string {
    const out: string[] = [];
    for (let i = 0; i < count; i++) {
        const w = WORDS[Math.floor(Math.random() * WORDS.length)];
        out.push(w);
    }
    return out.join(" ");
}
