export const SENTENCES: string[] = [
    "The sky is clear today.",
    "Time moves faster than we think.",
    "Practice makes everything better.",
    "The computer froze again.",
    "Coffee keeps me awake.",
    "Dreams inspire great ideas.",
    "Stay calm and keep going.",
    "Nothing lasts forever.",
    "The cat jumped over the box.",
    "Hard work always pays off.",
    "Success is built from small, consistent efforts.",
    "The internet connection dropped unexpectedly.",
    "She found a hidden message inside the old book.",
    "Technology changes faster than people expect.",
    "Every challenge is an opportunity to grow.",
    "The weather forecast predicts heavy rain tonight.",
    "He spent hours practicing to perfect his skills.",
    "A single mistake can teach a valuable lesson.",
    "The train arrived earlier than scheduled today.",
    "Some problems require time and patience to solve.",
    "Creativity often appears when we stop forcing ourselves to think.",
    "The old library was filled with dusty books and forgotten stories.",
    "She realized that confidence comes from experience, not perfection.",
    "When working under pressure, staying organized becomes essential.",
    "The city lights reflected beautifully across the quiet river at night.",
    "Even the most complicated tasks become manageable when broken into smaller steps.",
    "Learning a new language can be challenging, but it opens countless opportunities.",
    "He discovered that good communication prevents most misunderstandings.",
    "The scientist spent years studying tiny details that most people overlooked.",
    "Moments of silence often help the mind find clarity and focus.",
    "The robot malfunctioned during the final test.",
    "She accidentally deleted the entire project folder.",
    "The elevator stopped between the eighth and ninth floor.",
    "A loud thunderstorm interrupted the peaceful night.",
    "He received an unexpected message from an old friend.",
    "The last piece of the puzzle was hidden under the chair.",
    "They built a small campfire beside the quiet lake.",
    "The password was easy to remember but hard to guess.",
    "She typed so fast that the keyboard nearly overheated.",
    "The mystery box contained nothing but a single feather.",
    "Fast typing requires rhythm and focus.",
    "Accuracy is more important than speed.",
    "Challenge yourself to type faster every day.",
    "Keep your eyes on the screen, not the keyboard.",
    "Warm up your fingers before starting the test.",
    "Mistakes help you improve your typing ability.",
    "Every second counts when the timer starts.",
    "Stay relaxed to maintain high accuracy.",
    "Speed grows naturally with consistent practice.",
    "Your hands know the keys better than your eyes.",

    // เพิ่มเติม – daily life
    "She woke up early to watch the sunrise from her balcony.",
    "The smell of fresh bread filled the small bakery every morning.",
    "He forgot his umbrella and got soaked in the heavy rain.",
    "The children laughed loudly as they ran through the park.",
    "He organized his desk to clear his mind before working.",
    "The alarm clock rang, but he pressed snooze three times.",
    "She wrote her goals on a small sticky note above her screen.",
    "The traffic was slower than usual because of the morning fog.",
    "He took a short walk to rest his eyes from the monitor.",
    "The tiny plant on the windowsill grew a new leaf today.",
    "She listened to soft music while reading her favorite novel.",
    "He cooked a simple meal and enjoyed the quiet evening.",
    "The cafe on the corner was crowded but surprisingly peaceful.",
    "She bought a new notebook to track her daily habits.",
    "He cleaned his room and found an old photo album.",
    "The dog barked excitedly when its owner entered the house.",
    "She wrote a letter instead of sending a quick text message.",
    "The classroom became silent as the exam papers were handed out.",
    "He saved money each month to travel to his dream destination.",

    // เพิ่มเติม – work & study
    "He reviewed his notes carefully before the important presentation.",
    "She asked clear questions to understand the difficult topic better.",
    "The deadline was close, but the team stayed calm and focused.",
    "He divided the large project into smaller, manageable tasks.",
    "She stayed after class to practice and improve her weak points.",
    "The meeting took longer than expected but ended with a good plan.",
    "He double-checked the report for spelling and formatting mistakes.",
    "She highlighted the most important ideas in the textbook.",
    "They discussed different solutions before choosing the final approach.",
    "He realized that planning ahead reduced his overall stress.",
    "She used a timer to stay focused during her study sessions.",
    "He created a to-do list and actually finished every item on it.",
    "They shared feedback politely and helped each other improve.",
    "She practiced public speaking in front of a mirror every night.",
    "He searched for examples online to understand the problem clearly.",
    "The professor encouraged students to ask questions without feeling shy.",
    "She backed up all her files to avoid losing her progress.",
    "He learned that consistency beats short bursts of intense effort.",
    "They celebrated finishing the long project with a simple team lunch.",

    // เพิ่มเติม – coding / tech
    "He spent an hour debugging a bug caused by a missing semicolon.",
    "The website looked fine on desktop but broke on mobile screens.",
    "She pushed her code to the repository and opened a pull request.",
    "The server restarted unexpectedly and logged a strange error message.",
    "He refactored messy functions into smaller, reusable components.",
    "She wrote unit tests to make sure the feature worked correctly.",
    "The app loaded faster after they optimized the API responses.",
    "He added helpful comments so others could understand the code easily.",
    "She learned that naming variables clearly saved time in the future.",
    "The dark theme of the editor helped reduce eye strain at night.",
    "He forgot to handle an edge case and the app crashed for some users.",
    "They reviewed each other's code and spotted subtle performance issues.",
    "She documented the setup steps to help new team members join quickly.",
    "He used version control to safely experiment with different approaches.",
    "The new feature passed all tests but failed in real user conditions.",
    "She used keyboard shortcuts to navigate the editor much faster.",
    "He monitored the logs to find patterns in the reported errors.",
    "They deployed the updated app and watched the metrics in real time.",
    "She fixed a bug that bothered users for several weeks.",

    // เพิ่มเติม – mindset & motivation
    "Small improvements made every day create big changes over time.",
    "He reminded himself that progress matters more than perfection.",
    "She started slowly but never stopped moving forward.",
    "Failure became a lesson instead of a final result.",
    "He chose to focus on what he could control.",
    "She learned to rest instead of completely giving up.",
    "They supported each other's goals and shared honest encouragement.",
    "He tracked his progress to stay motivated on difficult days.",
    "She realized that comparing herself to others only slowed her down.",
    "He took a deep breath before dealing with a stressful situation.",
    "She accepted that learning new skills feels uncomfortable at first.",
    "He focused on the process instead of worrying about the outcome.",
    "She noticed that gratitude made stressful days feel lighter.",
    "They celebrated small wins to keep their spirits high.",
    "He learned to say no to distractions that wasted his time.",
    "She replaced negative thoughts with simple, realistic statements.",
    "He paused for a moment to think before reacting emotionally.",
    "She wrote down three good things that happened each day.",

    // เพิ่มเติม – misc & “fun” ประโยค
    "The cat stared at the cursor moving across the bright screen.",
    "He accidentally sent a funny sticker to the wrong group chat.",
    "She laughed when the autocorrect completely changed her sentence.",
    "The phone battery died just before he could save the document.",
    "He tried to balance a cup of coffee and his laptop in one hand.",
    "She almost typed her password into the search bar.",
    "The notification sound interrupted the quiet room again.",
    "He found an old game that still worked perfectly on his computer.",
    "She bought a mechanical keyboard just for the typing sound.",
    "He took a screenshot instead of writing the information down.",
    "The progress bar stopped at ninety-nine percent and stayed there.",
    "She renamed a file three times before choosing a final name.",
    "He accidentally opened fifty browser tabs while researching one topic.",
    "The Wi-Fi disconnected right before the important online meeting.",
    "She muted all notifications to finish her work without interruption.",
    "He used a random name generator to create test user accounts.",
    "The cursor blinked on an empty line, waiting for an idea.",
    "She changed the wallpaper to make her desktop feel fresh again.",
    "He smiled when the test finally passed with a green checkmark.",
    "She closed her laptop and decided the day was finally over.",
];

export const WORDS: string[] = [
    // basic / common
    "the",
    "quick",
    "brown",
    "fox",
    "jumps",
    "over",
    "lazy",
    "dog",
    "cat",
    "bird",
    "coffee",
    "tea",
    "water",
    "keyboard",
    "screen",
    "monitor",
    "mouse",
    "window",
    "door",
    "table",
    "chair",
    "phone",
    "laptop",
    "notebook",
    "pencil",
    "paper",
    "folder",
    "office",
    "school",
    "library",
    "classroom",
    "teacher",
    "student",
    "friend",
    "message",
    "email",
    "letter",
    "character",
    "space",
    "enter",
    "shift",
    "control",
    "tab",
    "escape",

    // typing / performance
    "typing",
    "practice",
    "speed",
    "accuracy",
    "rhythm",
    "effort",
    "focus",
    "energy",
    "habit",
    "routine",
    "progress",
    "result",
    "session",
    "warmup",
    "test",
    "sample",
    "target",
    "mistake",
    "correction",
    "timing",
    "reaction",
    "pressure",
    "performance",
    "stamina",
    "consistency",
    "improvement",

    // feelings / mindset
    "calm",
    "relaxed",
    "brave",
    "patient",
    "curious",
    "confident",
    "grateful",
    "careful",
    "focused",
    "motivated",
    "tired",
    "sleepy",
    "nervous",
    "excited",
    "optimistic",
    "hopeful",
    "quiet",
    "peaceful",
    "stress",
    "doubt",
    "fear",
    "courage",
    "effort",
    "growth",
    "progress",

    // time / schedule
    "time",
    "minute",
    "second",
    "hour",
    "morning",
    "noon",
    "evening",
    "night",
    "deadline",
    "schedule",
    "routine",
    "break",
    "moment",
    "today",
    "tomorrow",
    "yesterday",
    "later",
    "soon",
    "someday",
    "always",
    "never",

    // colors
    "green",
    "red",
    "yellow",
    "blue",
    "black",
    "white",
    "purple",
    "orange",
    "pink",
    "gray",
    "gold",
    "silver",

    // tech / coding
    "python",
    "typescript",
    "javascript",
    "react",
    "nextjs",
    "node",
    "server",
    "client",
    "frontend",
    "backend",
    "request",
    "response",
    "status",
    "error",
    "warning",
    "success",
    "failure",
    "debug",
    "feature",
    "commit",
    "branch",
    "merge",
    "deploy",
    "release",
    "version",
    "update",
    "rollback",
    "log",
    "console",
    "editor",
    "terminal",
    "command",
    "shortcut",
    "syntax",
    "runtime",
    "package",
    "module",
    "import",
    "export",
    "variable",
    "function",
    "constant",
    "array",
    "object",
    "string",
    "number",
    "boolean",
    "null",
    "undefined",
    "promise",
    "async",
    "await",
    "testcase",
    "coverage",
    "refactor",
    "cleanup",

    // UI / design
    "button",
    "input",
    "label",
    "form",
    "layout",
    "margin",
    "padding",
    "border",
    "radius",
    "shadow",
    "hover",
    "active",
    "focus",
    "disabled",
    "icon",
    "avatar",
    "dropdown",
    "sidebar",
    "navbar",
    "footer",
    "header",
    "card",
    "panel",
    "dialog",
    "modal",
    "overlay",

    // random nouns
    "river",
    "mountain",
    "forest",
    "ocean",
    "island",
    "village",
    "city",
    "bridge",
    "station",
    "ticket",
    "train",
    "bus",
    "airport",
    "flight",
    "camera",
    "photo",
    "picture",
    "memory",
    "story",
    "chapter",
    "poem",
    "novel",

    // verbs
    "run",
    "walk",
    "sleep",
    "eat",
    "drink",
    "write",
    "read",
    "listen",
    "speak",
    "study",
    "learn",
    "practice",
    "repeat",
    "review",
    "focus",
    "plan",
    "organize",
    "create",
    "build",
    "design",
    "fix",
    "break",
    "open",
    "close",
    "save",
    "cancel",
    "submit",
    "upload",
    "download",

    // misc useful words
    "simple",
    "complex",
    "random",
    "manual",
    "automatic",
    "hidden",
    "visible",
    "public",
    "private",
    "global",
    "local",
    "smooth",
    "sharp",
    "fast",
    "slow",
    "early",
    "late",
    "basic",
    "advanced",
    "common",
    "rare",
    "similar",
    "different",
];

export function buildWordsText(count: number): string {
    const out: string[] = [];
    for (let i = 0; i < count; i++) {
        const w = WORDS[Math.floor(Math.random() * WORDS.length)];
        out.push(w);
    }
    return out.join(" ");
}
